<?php

$concerts = array(
	array(
		'id' => '1542124855-593634828',
		'day' => '18',
		'month' => '06',
		'year' => '2010',
		'name' => array('Eindexam Janet Forbes', 'Overtones of melancholy, aftertaste of mirth'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Janet] Forbes'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '254836720-945257380',
		'day' => '15',
		'month' => '06',
		'year' => '2010',
		'name' => array('Eindexam Lovorka Holjevac'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Lovorka] Holjevac'),
		'genre' => array('Jazz'),
	),
	array(
		'preview' => true,
		'id' => '1970512283-2074564627',
		'day' => '13',
		'month' => '06',
		'year' => '2010',
		'where' => '[Koninklijk Conservatorium]',
		'name' => array('Contact'),
		'ensemble' => array('[Acid Police]'),
		'performers' => array('[Belinda] Li'),
		'pieces' => array('[Stefani Germanotta Blues Explosion]'),
		'genre' => array('Contemporary', 'Electronic', 'Dance'),
	),
	array(
		'preview' => true,
		'id' => '1658869099-295857131',
		'day' => '08',
		'month' => '06',
		'year' => '2010',
		'name' => array('NEW Festival', 'Eindexam Margriet van Duijvenbode'),
		'where' => '[De Regentes]',
		'performers' => array('[Margriet] van Duijvenbode'),
		'genre' => array('Jazz'),
	),
	array(
		'id' => '368975509-1351400968',
		'day' => '07',
		'month' => '06',
		'year' => '2010',
		'name' => array('DHA$ Composition Competition'),
		'composers' => array('[Tom Aldrich]', '[Grzegorz] Marciniak', '[David] Pocknee', 'Corne', '[Taylan] Susam'),
		'where' => '[Studio LOOS]',
		'ensemble' => array('Den Haag Allstars'),
		'genre' => array('Contemporary'),
	),
	array(
		'preview' => true,
		'id' => '1802184639-1442423250',
		'day' => '06',
		'month' => '06',
		'year' => '2010',
		'name' => array('Timeframes'),
		'where' => '[Barthkapel]',
		'ensemble' => '[Modelo62]',
		'performers' => array('[Ezequiel] Menalled'),
		'composers' => array('Teodora'),
		'genre' => array('Contemporary'),
	),
	array(
		'preview' => true,
		'id' => '1349531944-421870492',
		'day' => '03',
		'month' => '06',
		'year' => '2010',
		'name' => array('PIP Smaller Mafia Captains'),
		'ensemble' => array('[Acid Police]'),
		'where' => '[PIP]',
		'genre' => array('Contemporary', 'Electronic'),
	),
	array(
		'preview' => true,
		'id' => '1348809296-312689907',
		'day' => '27',
		'month' => '05',
		'year' => '2010',
		'name' => array('Benjamin Rhodes Debut Show'),
		'where' => '[Paard van Troje]',
		'performers' => array('[Jochanan] Samama', '[Margriet] van Duijvenbode'),
		'genre' => array('Jazz'),
	),
	array(
		'preview' => true,
		'id' => '637429873-95196582',
		'day' => '27',
		'month' => '05',
		'year' => '2010',
		'name' => array('Metamorphoses'),
		'ensemble' => array('[MAE Ensemble]'),
		'composers' => array('[Jeremiah] Runnels', '[Tomo]hisa Hashimoto'),
		'performers' => array(),
		'where' => '[Orgelpark]',
		'genre' => array('Contemporary', 'Dance'),
	),
	array(
		'preview' => true,
		'id' => '1680845070-2095023258',
		'day' => '25',
		'month' => '05',
		'year' => '2010',
		'name' => array('Chance Nova', 'Eindexam Yedo &amp; Jeremiah'),
		'composers' => array('[Jeremiah] Runnels', '[Yedo] Gibson'),
		'performers' => array('Teodora'),
		'ensemble' => array('[Big Foreigners Orchestra]'),
		'where' => '[Koninklijk Conservatorium]',
		'genre' => array('Contemporary'),
	),
	array(
		'preview' => true,
		'id' => '1997575230-1067986818',
		'day' => '22',
		'month' => '05',
		'year' => '2010',
		'name' => array('Amsterdam Composers&rsquo; Festival'),
		'performers' => array(),
		'where' => '[Conservatorium van Amsterdam]',
		'genre' => array('Contemporary'),
	),
	array(
		'preview' => true,
		'id' => '543674236-1793577684',
		'day' => '21',
		'month' => '05',
		'year' => '2010',
		'name' => array('Amsterdam Composers&rsquo; Festival'),
		'performers' => array(),
		'where' => '[Conservatorium van Amsterdam]',
		'genre' => array('Contemporary'),
	),
	array(
		'preview' => true,
		'id' => '432477998-980461570',
		'day' => '20',
		'month' => '05',
		'year' => '2010',
		'name' => array('Amsterdam Composers&rsquo; Festival'),
		'performers' => array(),
		'where' => '[Conservatorium van Amsterdam]',
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1558263656-979525257',
		'day' => '18',
		'month' => '05',
		'year' => '2010',
		'name' => array('Eindexam Bas Treub'),
		'performers' => array('[Bas] Treub'),
		'composers' => array('J.S. Bach', 'Schubert'),
		'where' => '[Koninklijk Conservatorium]',
		'genre' => array('Classical'),
	),
	array(
		'preview' => true,
		'id' => '798705916-1556329525',
		'day' => '18',
		'month' => '05',
		'year' => '2010',
		'name' => array('Calais Jungle', 'Eindexam Marie Guilleray'),
		'performers' => array('[Marie Guilleray]', 'Corne', '[Yedo] Gibson'),
		'where' => array('[Studio LOOS]', '[Koninklijk Conservatorium]'),
		'genre' => array('Jazz'),
	),
	array(
		'preview' => true,
		'id' => '608668209-24484264',
		'day' => '18',
		'month' => '05',
		'year' => '2010',
		'name' => array('Between Delirium and Sin', 'Eindexam Michal Bitan'),
		'performers' => array('[Michal] Bitan'),
		'where' => '[Koninklijk Conservatorium]',
		'genre' => array('Early Music'),
	),
	array(
		'preview' => true,
		'id' => '502902159-1317231895',
		'day' => '11',
		'month' => '05',
		'year' => '2010',
		'name' => array('Nicole Kidman #3'),
		'where' => '[Nicole Kidman Memorial Theater]',
		'ensemble' => array('Den Haag Allstars'),
		'performers' => array('[Germaine] Sijstermans'),
		'composers' => array('[Jeremiah] Runnels', 'Teodora', '[Ingi] Gar&eth;ar', '[Graham] Flett'),
		'genre' => array('Contemporary'),
		'pieces' => array('[Grote Harlequin]'),
	),
	array(
		'preview' => true,
		'id' => '270627950-448721563',
		'day' => '08',
		'month' => '05',
		'year' => '2010',
		'name' => array('Nutshuis TEST'),
		'where' => '[Nutshuis]',
		'performers' => array('[Pieter] De Buck', 'Michal Osowski'),
		'composers' => array('[Jeremiah] Runnels'),
		'genre' => array('Contemporary', 'Dance', 'Installation'),
		'pieces' => array('New Primitive Acoustics', '[Local Warming]'),
	),
	array(
		'preview' => true,
		'id' => '958185268-1651380104',
		'day' => '06',
		'month' => '05',
		'year' => '2010',
		'name' => array('Sonology concert'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Jakob] Leben', '[Michalis] Paraskakis'),
		'composers' => array('[Belinda] Li'),
		'genre' => array('Electronic', 'Dance'),
	),
	array(
		'id' => '35859838-1333534189',
		'day' => '06',
		'month' => '05',
		'year' => '2010',
		'name' => array('Exam Maciej Wierzcho&#322;owski'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Maciej] Wierzcho&#322;owski'),
		'genre' => array('Early Music'),
	),
	array(
		'preview' => true,
		'id' => '1469098283-1627945391',
		'day' => '29',
		'month' => '04',
		'year' => '2010',
		'name' => array('Eindexam Reinhard Wilkens'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Reinhard] Wilkens', '[Belinda] Li', '[Jade] Stenhuijs'),
		'composers' => array('Iannis Xenakis'),
		'pieces' => array('Rebonds B'),
		'genre' => array('Contemporary', 'Dance'),
	),
	array(
		'preview' => true,
		'id' => '126089567-1617447411',
		'day' => '27',
		'month' => '04',
		'year' => '2010',
		'name' => array('Live Electronics Workshop'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Kate] Cunningham', '[Ofir] Klemperer'),
		'composers' => array('[Maya] Verlaak', 'Thrainn', 'Wouter Snoei'),
		'genre' => array('Electronic'),
	),
	array(
		'id' => '944060182-875777446',
		'day' => '27',
		'month' => '04',
		'year' => '2010',
		'name' => array('Eindexam Elisenda Pujals'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Elisenda] Pujals', 'Teodora'),
		'composers' => array('John Cage', 'Erik Satie'),
		'genre' => array('Early Music', 'Contemporary'),
	),
	array(
		'id' => '510978954-1159132531',
		'day' => '27',
		'month' => '04',
		'year' => '2010',
		'name' => array('Eindexam Inbal Hever'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Inbal] Hever', 'Teodora'),
		'composers' => array('J.P. Rameau', 'Igor Stravinsky', '[Kornilios] Selamsis'),
		'genre' => array('Early Music', 'Contemporary'),
	),
	array(
		'id' => '1314981513-828418761',
		'day' => '18',
		'month' => '04',
		'year' => '2010',
		'name' => array('2-10 Minutes'),
		'where' => '[Studio LOOS]',
		'ensemble' => array('Den Haag Allstars'),
		'composers' => array('Teodora', '[Jeremiah] Runnels', '[Erik] Stifjell'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1261996900-669735707',
		'day' => '16',
		'month' => '04',
		'year' => '2010',
		'name' => array('Spring Festival 2010'),
		'where' => '[Koninklijk Conservatorium]',
		'ensemble' => array('[Ligeti Academy]'),
		'composers' => array('[Michael Gordon]', '[Diderik Wagenaar]'),
		'pieces' => array('Water Instrumental'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '652471753-964950598',
		'day' => '15',
		'month' => '04',
		'year' => '2010',
		'name' => array('Spring Festival 2010'),
		'where' => '[Koninklijk Conservatorium]',
		'ensemble' => array('[Ensemble Royaal]'),
		'composers' => array('[Diderik Wagenaar]', '[Chad Langford]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '990435096-672299066',
		'day' => '15',
		'month' => '04',
		'year' => '2010',
		'name' => array('Spring Festival 2010', 'New student works'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Yedo] Gibson'),
		// 'composers' => array(''),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '959745060-1954704739',
		'day' => '15',
		'month' => '04',
		'year' => '2010',
		'name' => array('Spring Festival 2010', 'Piano concert'),
		'where' => '[Koninklijk Conservatorium]',
		'ensemble' => array('[Acid Police]'),
		'performers' => array('[Leo] Svirsky'),
		'composers' => array('[Robert Blatt]', '[Cornelis de Bondt]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1195511828-20506284',
		'day' => '14',
		'month' => '04',
		'year' => '2010',
		'name' => array('Dissolve: Rituals'),
		'where' => '[Studio LOOS]',
		'ensemble' => array('[MAE Ensemble]'),
		'composers' => array('Teodora', 'Jasna', '[Hugo] Morales'),
		'pieces' => array('Everybody pays attention to the things in space, but nobody pays attention to the space itself'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1684120782-1318631062',
		'day' => '14',
		'month' => '04',
		'year' => '2010',
		'name' => array('Spring Festival 2010', 'Vocal Project'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Gustaf] Holst', '[Michalis] Paraskakis', '[Leo] Svirsky'),
		'composers' => array('[Diderik Wagenaar]', '[Jeremiah] Runnels', '[Maya] Verlaak'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1205219321-1869778344',
		'day' => '14',
		'month' => '04',
		'year' => '2010',
		'name' => array('Spring Festival 2010', 'Percussion project'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Jeremiah] Runnels', '[Gustaf] Holst', '[Inbal] Hever'),
		'composers' => array('[Renato] Ferreira', '[Kornilios] Selamsis'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1389221976-1560904040',
		'day' => '13',
		'month' => '04',
		'year' => '2010',
		'name' => array('Kick the Can'),
		'where' => array('van Rotterdam t/m Den Haag', '[PIP]'),
		'ensemble' => array('[Acid Police]'),
		'performers' => array('[Jeremiah] Runnels', '[Kornilios] Selamsis'),
		'composers' => array('Louis Andriessen', 'John Cage', '[Ofir] Klemperer'),
		'pieces' => array('De Staat', '4:33', 'ook series concertposters'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '836113824-1378944805',
		'day' => '12',
		'month' => '04',
		'year' => '2010',
		'name' => array('Spring Festival 2010', 'New York The Hague'),
		'where' => '[Korzo]',
		'ensemble' => array('[Bang on a Can All-stars]'),
		'composers' => array('[Cornelis de Bondt]', '[Martijn Padding]', '[Angus] Barnacle'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '350839413-1480563968',
		'day' => '15',
		'month' => '02',
		'year' => '2010',
		'name' => array('Nutshuis TEST'),
		'where' => '[Nutshuis]',
		'ensemble' => '[Modelo62]',
		'performers' => array('[Ezequiel] Menalled', 'Teodora'),
		'composers' => array('[Renato] Ferreira', '[Maya] Verlaak'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '78505901-1830900869',
		'day' => '12',
		'month' => '02',
		'year' => '2010',
		'name' => array('Njwebyrth', 'Love Songs'),
		'where' => '[Korzo]',
		'performers' => array('[Lilith] Verhelst', '[Soren] Green', '[Anton] Baba'),
		'composers' => array('[Niels Berentsen]', '[Angus] Barnacle', '[Diego] Soifer'),
		'genre' => array('Early Music', 'Contemporary'),
	),
	array(
		'id' => '1789093106-746011888',
		'day' => '01',
		'month' => '02',
		'year' => '2010',
		'name' => array('Hammond Organ Festival'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('Teodora', '[Ingi] Gar&eth;ar', '[Belinda] Li', '[Kate] Cunningham'),
		'composers' => array('[Karlheinz Stockhausen]', '[Jeremiah] Runnels', 'Teodora'),
		'pieces' => array('Mikrofonie II', '[Glory]', '[Hammond MP3 piece]'),
		'genre' => array('Electronic', 'Contemporary'),
	),
	array(
		'id' => '23082680-1246732678',
		'day' => '23',
		'month' => '01',
		'year' => '2010',
		'name' => array('Nutshuis TEST'),
		'where' => '[Nutshuis]',
		'ensemble' => array('Den Haag Allstars'),
		'composers' => array('Teodora', '[Tomo]hisa Hashimoto'),
		'pieces' => array('Ropes, Strings, Poppea &amp; 3 stories by Daniil Kharms', 'Chalk', 'Roce to one'),
		'genre' => array('Contemporary', 'Dance'),
	),
	array(
		'id' => '444351163-171737624',
		'day' => '22',
		'month' => '12',
		'year' => '2009',
		'name' => array('KoMA &lsquo;6'),
		'where' => '[Belgrade], Serbia',
		'performers' => array('Teodora'),
		'composers' => array('Teodora', '[Hugo] Morales', '[Chad Langford]'),
		'pieces' => array('[Still No Title]', '[Rivers of Europe]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1807824845-1430555079',
		'day' => '06',
		'month' => '12',
		'year' => '2009',
		'name' => array('Nutshuis TEST'),
		'where' => '[Nutshuis]',
		'ensemble' => array('Den Haag Allstars'),
		'composers' => array('Thrainn', '[Jeremiah] Runnels', 'Teodora'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1451149058-1490358751',
		'day' => '02',
		'month' => '12',
		'year' => '2009',
		'name' => array('DHA$ @ LOOS'),
		'where' => '[Studio LOOS]',
		'ensemble' => array('Den Haag Allstars'),
		'composers' => array('Teodora', '[Jeremiah] Runnels'),
		'pieces' => array('Re/De/Construction'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '2073871409-1786326201',
		'day' => '01',
		'month' => '12',
		'year' => '2009',
		'name' => array('Project Ascoli'),
		'where' => '[Koninklijk Conservatorium]',
		'ensemble' => array('[Ascoli Ensemble]'),
		'composers' => array('[Sasha] Zamler-Carhart'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '243084711-10171598',
		'day' => '30',
		'month' => '11',
		'year' => '2009',
		'name' => array('KC Lab'),
		'where' => '[Korzo]',
		'ensemble' => array('Den Haag Allstars'),
		'performers' => array('[Leo] Svirsky', '[James Hewitt]'),
		'composers' => array('Teodora', '[Chad Langford]'),
		'pieces' => array('[Marco Polo]', '[Rivers of Europe]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1880283179-280823615',
		'day' => '28',
		'month' => '11',
		'year' => '2009',
		'name' => array('Flute concert'),
		'where' => '[Remonstrantse Kerk]',
		'performers' => array('[Emeline] Dessi', '[Joost] Gevers', '[Zuid-Holland Symfonie Orkest]'),
		'composers' => array('Devienne', 'Debussy', 'Ravel'),
		'pieces' => array('Concerto for flute in e minor'),
		'genre' => array('Classical'),
	),
	array(
		'id' => '606538623-840919219',
		'day' => '27',
		'month' => '11',
		'year' => '2009',
		'name' => array('Dissolve: Rooms'),
		'where' => 'Theater [Kikker], Utrecht',
		'ensemble' => array('[MAE Ensemble]'),
		'composers' => array('Teodora', '[Hugo] Morales', '[Ezequiel] Menalled '),
		'pieces' => array('[Big Blue Blazer]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '251833621-1897617673',
		'day' => '26',
		'month' => '11',
		'year' => '2009',
		'name' => array('Royal Improvisers Orchestra'),
		'where' => '[Studio LOOS]',
		'ensemble' => array('[Royal Improvisers Orchestra]'),
		'performers' => array('[Marie Guilleray]'),
		'composers' => array('[Yedo] Gibson'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1851033076-944405707',
		'day' => '21',
		'month' => '11',
		'year' => '2009',
		'name' => array('Purcell concert'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Maciej] Wierzcho&#322;owski', '[David Greco]'),
		'composers' => array('Henry Purcell'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '',
		'day' => '16',
		'month' => '11',
		'year' => '2009',
		'name' => array('November music'),
		'where' => '[Koninklijk Conservatorium]',
		'ensemble' => '[Modelo62]',
		'performers' => array('[Ezequiel] Menalled', 'Teodora'),
		'composers' => array('[Justin] Christiansen', '[Ezequiel] Menalled'),
		'pieces' => array('Matter', 'La vida breve'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1453432235-980651705',
		'day' => '07',
		'month' => '11',
		'year' => '2009',
		'name' => array('Nutshuis TEST'),
		'where' => '[Nutshuis]',
		'performers' => array('Teodora', '[Chad Langford]', '[Emeline] Dessi', '[Aldo] Aranda'),
		'composers' => array('[Rob Manthey]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '741292867-944643884',
		'day' => '06',
		'month' => '11',
		'year' => '2009',
		'name' => array('Bach op Vrijdag'),
		'where' => '[Lutherse Kerk]',
		'performers' => array('[Michal] Bitan', '[Laura Bell]'),
		'composers' => array('J.S. Bach'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '2116930374-1385523072',
		'day' => '05',
		'month' => '10',
		'year' => '2009',
		'name' => array('Nutshuis TEST'),
		'where' => '[Nutshuis]',
		'performers' => array('Hans [Eberhard] Maldfeld', '[Kate] Cunningham'),
		'composers' => array('[Jeremiah] Runnels'),
		'pieces' => array('[The Death of Hippasus]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1530468701-1114497180',
		'day' => '02',
		'month' => '10',
		'year' => '2009',
		'name' => array('Bach op Vrijdag'),
		'where' => '[Lutherse Kerk]',
		'performers' => array('[Maciej] Wierzcho&#322;owski', '[Oscar Verhaar]'),
		'composers' => array('J.S. Bach'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '1076676144-524913595',
		'day' => '22',
		'month' => '09',
		'year' => '2009',
		'name' => array('String Maiden'),
		'where' => '[Nicole Kidman Memorial Theater]',
		'performers' => array('[Bobby] Mitchell', '[Taylan] Susam', '[Pieter] De Buck'),
		'composers' => array('[Jeremiah] Runnels'),
		'pieces' => array('New Primitive Acoustics', 'Celesta Redux'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1040223757-78814938',
		'day' => '21',
		'month' => '09',
		'year' => '2009',
		'name' => array('Improvization evening'),
		'where' => '[Studio LOOS]',
		'performers' => array('Ofer Bymel', 'Adi Snir', '[Ingi] Gar&eth;ar', '[Miguelangel] Clerc'),
		'composers' => array('Teodora', '[Miguelangel] Clerc'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '2036535380-1729444032',
		'day' => '09',
		'month' => '08',
		'year' => '2009',
		'name' => array('Brass Maiden'),
		'where' => '[Nicole Kidman Memorial Theater]',
		'performers' => array('Peter Blasser', 'Michal Osowski', '[Pieter] De Buck'),
		'composers' => array('[Jeremiah] Runnels'),
		'pieces' => array('New Primitive Acoustics', 'Hermetic Breakdances'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '668938992-1131410038',
		'day' => '27',
		'month' => '06',
		'year' => '2009',
		'name' => array('Royal Improvisers Orchestra'),
		'where' => array('[Muziekgebouw] aan &rsquo;t IJ', '[Bimhuis]'),
		'ensemble' => array('[Royal Improvisers Orchestra]'),
		'performers' => array('[Marie Guilleray]'),
		'composers' => array('[Yedo] Gibson'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1328938867-2042688077',
		'day' => '24',
		'month' => '06',
		'year' => '2009',
		'name' => array('Sonology concert'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('Teodora'),
		'composers' => array('[Filipe] Lopes'),
		'pieces' => array('Odaiko 10'),
		'genre' => array('Electronic'),
	),
	array(
		'id' => '644660284-1109062095',
		'day' => '20',
		'month' => '06',
		'year' => '2009',
		'name' => array('Roz&eacute; Zaterdag'),
		'where' => 'Het [Plein], Den Haag',
		'performers' => array('Lesbokoor de Heksenketel', '[Maciej] Wierzcho&#322;owski'),
		'composers' => array('Robbie Williams'),
		'pieces' => array('Angels'),
		'genre' => array('Choral'),
	),
	array(
		'id' => '234887525-721741303',
		'day' => '15',
		'month' => '06',
		'year' => '2009',
		'name' => array('Eindexam Elyssa Shala'),
		'where' => '[Nutshuis]',
		'performers' => array('[Elyssa] Shala', '[Matthew] Jenkins'),
		'composers' => array('[Elyssa] Shala'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '668828447-1972995287',
		'day' => '14',
		'month' => '06',
		'year' => '2009',
		'name' => array('Eindexam Diego Soifir &amp; Graham Flett'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Lovorka] Holjevac', '[Ingi] Gar&eth;ar '),
		'composers' => array('[Diego] Soifer', '[Graham] Flett', 'Teodora'),
		'pieces' => array('09 &agrave; la Kusturica'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1651548683-1982187213',
		'day' => '13',
		'month' => '06',
		'year' => '2009',
		'name' => array('Festival Classique'),
		'where' => '[Hofvijver], Den Haag',
		'performers' => array('New Dutch Academy', 'Reut Rivka'),
		'composers' => array('Henry Purcell'),
		'pieces' => array('Dideo & Aeneas'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '1892645672-221759663',
		'day' => '08',
		'month' => '06',
		'year' => '2009',
		'name' => array('Nutshuis TEST'),
		'where' => '[Nutshuis]',
		'performers' => array('[Bobby] Mitchell', '[Graham] Flett'),
		'composers' => array('Teodora', '[Tomo]hisa Hashimoto'),
		'genre' => array('Contemporary', 'Dance'),
	),
	array(
		'id' => '1581373214-1222022199',
		'day' => '02',
		'month' => '06',
		'year' => '2009',
		'name' => array('Eindexam Teodora Stepan&#269;i&#263; &amp; Ingi Gar&eth;ar'),
		'where' => '[Binckhorst]',
		'performers' => array('Teodora', '[Ingi] Gar&eth;ar', '[Lovorka] Holjevac'),
		'composers' => array('Teodora', '[Lilith] Gar&eth;ar'),
		'pieces' => array('[Aluminum Obsession]', '[Trombone in a Can]', '[Still No Title]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '150734787-223056279',
		'day' => '20',
		'month' => '05',
		'year' => '2009',
		'name' => array('Eindexam Camille Hesketh'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Camille] Hesketh', '[James Hewitt]'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '2067708685-640050040',
		'day' => '16',
		'month' => '05',
		'year' => '2009',
		'name' => array('Zenith Festival'),
		'where' => '[Paleiskerk]',
		'composers' => array('Jiri', '[Janco] Verduin'),
		'genre' => array('Classical'),
	),
	array(
		'id' => '407776159-714630626',
		'day' => '04',
		'month' => '05',
		'year' => '2009',
		'name' => array('Scared & Unprepared'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('Jiri', '[Belinda] Li', '[Pieter] De Buck'),
		'composers' => array('[Jeremiah] Runnels', '[Sander] Breure'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '960716551-777391133',
		'day' => '03',
		'month' => '05',
		'year' => '2009',
		'name' => array('Njwebyrth'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Lilith] Verhelst', '[Rebecca Huber]', '[Laura Bell]'),
		'composers' => array('[Pelopre]'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '128325411-2012430472',
		'day' => '28',
		'month' => '04',
		'year' => '2009',
		'name' => array('Early Music Open Stage'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Sasha] Zamler-Carhart', '[Manoj] Kamps'),
		'composers' => array('[Sasha] Zamler-Carhart'),
		'pieces' => array('Scarborough Fair'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '881709222-1005653131',
		'day' => '28',
		'month' => '04',
		'year' => '2009',
		'name' => array('Spring Festival 2009'),
		'where' => '[Korzo]',
		'ensemble' => array('[Nieuw Ensemble]'),
		'composers' => array('[Graham] Flett', '[Lucas] Wiegerink', '[Nicoleta] Chatzopoulou'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1470917875-1748812450',
		'day' => '24',
		'month' => '04',
		'year' => '2009',
		'name' => array('Handel Project'),
		'where' => array('[Grote Kerk], Den Haag', '[Groningen]', '[Deventer]'),
		'performers' => array('[Peter Van Heyghen]', 'student orchestra'),
		'composers' => array('G.F. Handel', '[Jeremiah] Runnels'),
		'pieces' => array('This is the Day', '[MP3 player piece]'),
		'genre' => array('Early Music', 'Contemporary'),
	),
	array(
		'id' => '280009833-85249402',
		'day' => '23',
		'month' => '04',
		'year' => '2009',
		'name' => array('Spring Festival 2009', 'To You'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Elisenda] Pujals'),
		'composers' => array('Peter Schat'),
		'pieces' => array('To You'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '680476480-1055027968',
		'day' => '22',
		'month' => '04',
		'year' => '2009',
		'name' => array('Spring Festival 2009', 'Drinking Songs'),
		'where' => '[Koninklijk Conservatorium]',
		'ensemble' => array('[Rosa Ensemble]'),
		'composers' => array('Teodora', '[Tom Aldrich]', '[Ofir] Klemperer'),
		'pieces' => array('[Big Blue Blazer]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1537033413-34289885',
		'day' => '21',
		'month' => '04',
		'year' => '2009',
		'name' => array('Spring Festival 2009', 'Vocal project'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('Teodora', '[Jeremiah] Runnels', 'Andrew', '[Sasha] Zamler-Carhart'),
		'composers' => array('[Jeremiah] Runnels'),
		'pieces' => array('[The Sabines at Riverbank]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1681692777-846930886',
		'day' => '18',
		'month' => '04',
		'year' => '2009',
		'name' => array('Schoenburg Festival'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Christian Karlson]', 'student orchestra'),
		'composers' => array('Arnold Schoenburg'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1897679002-1715417226',
		'day' => '06',
		'month' => '04',
		'year' => '2009',
		'name' => array('KC Lab'),
		'where' => '[Korzo]',
		'ensemble' => '[Modelo62]',
		'performers' => array('[Ezequiel] Menalled', 'Teodora'),
		'composers' => array('[Jeremiah] Runnels', '[Yedo] Gibson'),
		'pieces' => array('[With a little help from my friendships]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1399151912-1690247794',
		'day' => '26',
		'month' => '03',
		'year' => '2009',
		'name' => array('Installaties'),
		'where' => '[Nutshuis]',
		'composers' => array('[Sander] Breure', '[Tomo]hisa Hashimoto'),
		'pieces' => array('[Life Area]', 'You&rsquo;ll Never Walk Alone'),
		'genre' => array('Installation', 'Video'),
	),
	array(
		'id' => '1164036763-1502183997',
		'day' => '16',
		'month' => '02',
		'year' => '2009',
		'name' => array('KC Lab'),
		'where' => '[Korzo]',
		'performers' => array('[Mikael] Szafirowski', '[Berta] Puigdemasa'),
		'composers' => array('[Ofir] Klemperer', '[Jeremiah] Runnels'),
		'pieces' => array('[Vacuum Cleaner piece]'),
		'genre' => array('Contemporary', 'Electronic'),
	),
	array(
		'id' => '1027810610-2110298357',
		'day' => '15',
		'month' => '02',
		'year' => '2009',
		'name' => array('Nutshuis TEST'),
		'where' => '[Nutshuis]',
		'performers' => array('Jiri', '[Emma] Elkinson', '[Germaine] Sijstermans'),
		'composers' => array('[Rob Manthey]', 'Teodora'),
		'pieces' => array('[Ritual]', '[Stairs piece]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '876441943-573069909',
		'day' => '03',
		'month' => '02',
		'year' => '2009',
		'name' => array('Sonology concert'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('Teodora'),
		'composers' => array('[Filipe] Lopes'),
		'pieces' => array('Odaiko 10'),
		'genre' => array('Electronic'),
	),
	array(
		'id' => '1410626775-1315108254',
		'day' => '07',
		'month' => '12',
		'year' => '2008',
		'name' => array('Nutshuis TEST'),
		'where' => '[Nutshuis]',
		'ensemble' => array('[Big Ensemble]'),
		'performers' => array('[Bobby] Mitchell'),
		'composers' => array('[Rob Manthey]', '[Diego] Soifer', 'Tom Aldrich'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '888998798-43126694',
		'day' => '01',
		'month' => '12',
		'year' => '2008',
		'name' => array('KC Lab'),
		'where' => '[Korzo]',
		'performers' => array('[Jon Berman]', '[Renato] Ferreira', '[Chad Langford]'),
		'composers' => array('Teodora', '[Jeremiah] Runnels'),
		'pieces' => array('[Focus 7.3.8]', '[Symphony in C Major]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '944979032-831226944',
		'day' => '17',
		'month' => '11',
		'year' => '2008',
		'name' => array('Richard Rijnvos festival'),
		'where' => array('Koninklijk Conservatorium', '[Korzo]'),
		// 'performers' => array('[Jon Berman]', '[Renato] Ferreira', '[Chad Langford]'),
		'composers' => array('Richard Rijnvos'),
		// 'pieces' => array('[Focus 7.3.8]', '[Symphony in C Major]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1999946604-2052480242',
		'day' => '13',
		'month' => '10',
		'year' => '2008',
		'name' => array('SZ: The Nutshuis project'),
		'where' => '[Nutshuis]',
		'ensemble' => array('Ensemble [SZ]'),
		'composers' => array('Teodora', '[Miguelangel] Clerc', '[Grzegorz] Marciniak'),
		'pieces' => array('Bubblewrap piece'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '343978499-354831533',
		'day' => '10',
		'month' => '10',
		'year' => '2008',
		'name' => array('Stockhausen Studio dedication'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('Teodora', '[Kathinka Pasveer]'),
		'composers' => array('[Karlheinz Stockhausen]'),
		'pieces' => array('Klavierst&uuml;ck IX'),
		'genre' => array('Contemporary', 'Electronic'),
	),
	array(
		'id' => '',
		'day' => '18',
		'month' => '04',
		'year' => '2008',
		'name' => array('Spring Festival 2008'),
		'where' => '[Koninklijk Conservatorium]',
		'ensemble' => array('[POW Ensemble]'),
		'composers' => array('[James Hewitt]'),
		'genre' => array('Electronic'),
	),
	array(
		'id' => '',
		'day' => '17',
		'month' => '04',
		'year' => '2008',
		'name' => array('Spring Festival 2008'),
		'where' => '[Koninklijk Conservatorium]',
		'composers' => array('[Gilius van Bergelijk]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '850926921-1025803824',
		'day' => '16',
		'month' => '04',
		'year' => '2008',
		'name' => array('Spring Festival 2008', 'Blowjob piece'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Niels Berentsen]', '[Janet] Forbes', '[Andrew Hallock]'),
		'composers' => array('W.A. Mozart', '[Kornilios] Selamsis'),
		'genre' => array('Classical', 'Contemporary'),
	),
	array(
		'id' => '',
		'day' => '15',
		'month' => '04',
		'year' => '2008',
		'name' => array('Spring Festival 2008'),
		'where' => '[Koninklijk Conservatorium]',
		'ensemble' => array('Ensemble [SZ]'),
		'composers' => array('Teodora', '[Miguelangel] Clerc', '[Grzegorz] Marciniak'),
		'pieces' => array('Suco de luz'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '470739992-1932100355',
		'day' => '15',
		'month' => '04',
		'year' => '2008',
		'name' => array('Spring Festival 2008', 'Sound Salad'),
		'where' => '[Voorburg]',
		'performers' => array('[James Hewitt]', '[Janet] Forbes'),
		'composers' => array('[Pelopre]'),
		'pieces' => array('[The Devil Poisons James Hewitt]'),
		'genre' => array('Classical'),
	),
	array(
		'id' => '1141271123-1499353614',
		'day' => '20',
		'month' => '04',
		'year' => '2007',
		'name' => array('Spring Festival 2007'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Christian Karlson]', 'Teodora'),
		'composers' => array('[Jeremiah] Runnels', '[Miguelangel] Clerc'),
		'pieces' => array('[Dog whistle piece]', 'La linea desde el centro'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '1587249122-1811529143',
		'day' => '20',
		'month' => '04',
		'year' => '2007',
		'name' => array('Spring Festival 2007'),
		'where' => '[Koninklijk Conservatorium]',
		'composers' => array('[Sander] Breure', '[Witte] van Hulzen'),
		'pieces' => array('Just like you said it would be'),
		'genre' => array('Dance'),
	),
	array(
		'id' => '609996071-1359749363',
		'day' => '05',
		'month' => '03',
		'year' => '2007',
		'name' => array('KC Lab'),
		'where' => '[Korzo]',
		'composers' => array('[Sander] Breure', '[Witte] van Hulzen'),
		'pieces' => array('[Sander]&rsquo;s dance piece'),
		'genre' => array('Dance'),
	),
	array(
		'id' => '831975388-1653445750',
		'day' => '20',
		'month' => '11',
		'year' => '2006',
		'name' => array('KC Lab'),
		'where' => '[Korzo]',
		'performers' => array('[Jeremiah] Runnels', '[Elyssa] Shala', '[Taylan] Susam'),
		'composers' => array('[Jeremiah] Runnels'),
		'pieces' => array('[Dry Ice piece]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '648362456-638233250',
		'day' => '21',
		'month' => '04',
		'year' => '2006',
		'name' => array('Spring Festival 2006', 'Pork Skunk'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('[Juan Martinez]', 'Pepe'),
		'composers' => array('[Sasha] Zamler-Carhart'),
		'pieces' => array('[Death of the King of Bandjoun]'),
		'genre' => array('Contemporary'),
	),
	array(
		'id' => '441119139-1143681882',
		'day' => '20',
		'month' => '05',
		'year' => '2005',
		'name' => array('Recorder concert'),
		'where' => array('[Muziekgebouw] aan &rsquo;t IJ'),
		'performers' => array('Recorder consort', '[Andrew Hallock]'),
		'composers' => array('[Sasha] Zamler-Carhart'),
		'pieces' => array('Een nieuu musyckboexken, mit tien liedekens gecomponeert by diversche componisten, zeer lustisch om spelen op fluyten en cromhoornen, verzamelt en opnieuu bewerkt by s. zamler-carhart te \'s graven hage'),
		'genre' => array('Early Music'),
	),
	array(
		'id' => '1502984282-801137692',
		'day' => '16',
		'month' => '04',
		'year' => '2005',
		'name' => array('Spring Festival 2005', 'Beef Panda'),
		'where' => '[Koninklijk Conservatorium]',
		'performers' => array('Recorder consort', '[Andrew Hallock]'),
		'composers' => array('[Sasha] Zamler-Carhart'),
		'pieces' => array('Een nieuu musyckboexken, mit tien liedekens gecomponeert by diversche componisten, zeer lustisch om spelen op fluyten en cromhoornen, verzamelt en opnieuu bewerkt by s. zamler-carhart te \'s graven hage'),
		'genre' => array('Early Music'),
	),
);

?>
