<?php

$quotes = array(
	array('quote' => 'I love this game! I play it over the network and it never gets boring. I *will* take over the world!', 
		  'author' => 'G.D.'),
	array('quote' => 'Great app and fantastic to play against friends over the net... Graphics are top-notch and program is fast...', 
		  'author' => 'D.S.'),
	array('quote' => 'How I can get my son off that game? It&lsquo;s bloody addictive! I may need to get another Mac if he contiunes...', 
		  'author' => 'I.F.'),
	array('quote' => 'iConquer is one of the best apps for OS X!', 
		  'author' => 'J.H.'),
	array('quote' => 'I am totally addicted to this game!  Nice job &mdash; very fun and very elegant OS X design.', 
		  'author' => 'J.J.'),
	array('quote' => 'iConquer really is an awesome game. I play it constantly whenever I can talk any friends into it &mdash; and your implementation is slick, shiny and totally functional.  Extremely well done.', 
		  'author' => 'W.T.'),
	array('quote' => 'I abandoned my WarCraft 3 campaigns and StarCraft is compressed in a corner of my hard drive... this game owns all.', 
		  'author' => 'S.D.'),
	array('quote' => 'Nice Aqua graphics, along with an easy to use interface make this game one of my favorite time-killers.', 
		  'author' => 'B.K.'),
	array('quote' => 'You provide better customer service than the big companies with dedicated support staff.', 
		  'author' => 'V.P.'),
	array('quote' => 'iConquer is the best thing that has ever happened to my 17" MacBook Pro!', 
		  'author' => 'C.J.'),
	array('quote' => 'I love iConquer &mdash; it&lsquo;s easily the most fun I&lsquo;ve had playing a computer strategy game.', 
		  'author' => 'M.V.'),
	array('quote' => 'As many others have said, this is a fantastic game! It combines great looks, engaging game play, and slick performance.', 
		  'author' => 'D.K.'),
	array('quote' => 'Best $35 game since, well, ever!', 
		  'author' => 'S.M.'),
	array('quote' => 'Thank you for an incredible game. I&lsquo;m a Risk nut, and this just takes it to an entirely different level. I&lsquo;m one very happy customer.', 
		  'author' => 'R.A.'),
	array('quote' => 'I love the game and enjoy it immensely.  It&lsquo;s by far the best Risk implementation I&lsquo;ve seen &mdash; including the original board game!', 
		  'author' => 'K.B.'),
	array('quote' => 'Thanks so much for the super-excellent game!', 
		  'author' => 'B.M.'),
	array('quote' => 'I don&lsquo;t know how I&lsquo;d survive those tedious phone support calls without iConquer to distract me!', 
		  'author' => 'B.S.'),
	array('quote' => 'I want to congratulate you on a piece of software that makes my tedious tram trips to university somewhat bearable!', 
		  'author' => 'B.M.'),
	array('quote' => 'Your gameplay and graphics are astounding. I\'m really happy I found iConquer for playing during boring meetings!', 
		  'author' => 'P.D.'),
	array('quote' => 'Your program is the reason I bought a Mac. I love it!', 
		  'author' => 'K.F.'),
);

?>