<?php

$new_products = array('hyperimage');

$products = array(
	'shoebox_pro' => array(
		'icon' => 'Shoebox',
		'name' => 'Shoebox Pro',
		'slogan' => 'Organize your photos by content.',
		'price' => '80',
		'link' => 'Shoebox/index.php',
		'paypal_name' => 'Shoebox Pro',
		'kagi_name' => 'Shoebox_Pro_P2R', 
		'kagi_id' => '932466279333',
		'product_id' => 1,
		'protocol' => 'shoebox',
		'version' => '1.7.5',
		'size' => '4.9 MB',
		// 'whatsnew' => "Shoebox 1.7.6 brings several important stability improvements.",
		'release' => '2007/Shoebox17.txt',
		'screenshot_width' => 1225,
		'screenshot_height' => 759,
		'macosx' => '10.4',
	),
	'shoebox_express' => array(
		'icon' => 'Shoebox',
		'name' => 'Shoebox Express',
		'slogan' => 'Organize your photos by content.',
		'price' => '30',
		'link' => 'Shoebox/index.php',
		'paypal_name' => 'Shoebox Express',
		'kagi_name' => 'Shoebox_Express_P2R',
		'kagi_id' => '978797641025',
		'product_id' => 1,
		'protocol' => 'shoebox',
		'version' => '1.7.5',
		'size' => '4.9 MB',
		'macosx' => '10.4',
	),
	'iconquer' => array(
		'icon' => 'iConquer',
		'name' => 'iConquer',
		'slogan' => 'iCame, iSaw, iConquered.',
		'price' => '35',
		'link' => 'iConquer/index.php',
		'paypal_name' => 'iConquer 4',
		'kagi_name' => 'iConquer_4_P2R',
		'kagi_id' => '675077501053',
		'product_id' => 5,
		'protocol' => 'iconquer',
		'version' => '4.0',
		'size' => '9.1 MB',
		'whatsnew' => "The all-new iConquer 4 features high-definition maps of cities like New York, London and Paris, new AI computer adversaries, full screen mode, play-by-play game messages, heads-up display windows, and much more!",
/*		'upgrade' => array(
			'version_prefix' => '4',
			'whatsnew' => "The all-new iConquer 4 features high-definition maps of cities like New York, London and Paris, new AI computer adversaries, full screen mode, play-by-play game messages, heads-up display windows, and much more!",
			// 'image' => 'http://www.kavasoft.com/images/apps/KavaServices-512.png',
			'price' => '15',
		),
*/		'release' => '2010/iConquer40.txt',
		'screenshot_width' => 1150,
		'screenshot_height' => 796,
		'macosx' => '10.5',
	),
	'kavatunes' => array(
		'icon' => 'KavaTunes',
		'name' => 'KavaTunes',
		'slogan' => 'The web jukebox for iTunes.',
		'price' => '35',
		'link' => 'KavaTunes/index.php',
		'paypal_name' => 'KavaTunes 4',
		'kagi_name' => 'KavaTunes_4_P2R',
		'kagi_id' => '561765769228',
		'product_id' => 2,
		'protocol' => 'kavatunes',
		'version' => '4.0.2',
		'size' => '3.6 MB',
		'whatsnew' => "KavaTunes 4.0.2 now gets higher resolution artwork from iTunes.",
		'release' => '2009/KavaTunes40.txt',
		'screenshot_width' => 1200,
		'screenshot_height' => 781,
		'macosx' => '10.5',
	),
	'kavamovies' => array(
		'icon' => 'KavaMovies',
		'name' => 'KavaMovies',
		'slogan' => 'The Mac movie database.',
		'price' => '35',
		'link' => 'KavaMovies/index.php',
		'paypal_name' => 'KavaMovies',
		'kagi_name' => 'KavaMovies_P2R',
		'kagi_id' => '619990174301',
		'product_id' => 3,
		'protocol' => 'kavamovies',
		'version' => '1.5.2',
		'size' => '6.7 MB',
		'whatsnew' => "KavaMovies 1.5.2 includes support for IMDb's new layout.",
		'release' => '2010/KavaMovies15.txt',
		'screenshot_width' => 1024,
		'screenshot_height' => 728,
		'coming_soon' => false,
		'macosx' => '10.5',
	),
	'hyperimage' => array(
		'icon' => 'HyperImage',
		'name' => 'HyperImage',
		'slogan' => 'Download web photo galleries.',
		'price' => '25',
		'link' => 'HyperImage/index.php',
		'paypal_name' => 'HyperImage 3',
		'kagi_name' => 'HyperImage_P2R',
		'kagi_id' => '474825740087',
		'product_id' => 4,
		'protocol' => 'hyperimage',
		'version' => '3.5.1',
		'size' => '3.4 MB',
		'whatsnew' => "HyperImage 3.5.1 can now queue Tumblr posts inside the application.",
		'release' => '2010/HyperImage35.txt',
		'screenshot_width' => 1460,
		'screenshot_height' => 913,
		'macosx' => '10.6',
	),
	'kavaservices' => array(
		'icon' => 'KavaServices',
		'name' => 'KavaServices',
		'slogan' => 'Services menu utilities.',
		'price' => '25',
		'link' => 'KavaServices/index.php',
		'paypal_name' => 'KavaServices',
		'kagi_name' => 'KavaServices_P2R',
		'kagi_id' => '168460036183',
		'product_id' => 7,
		'protocol' => 'kavaservices',
		'version' => '4.3.1',
		'whatsnew' => "KavaServices 4.3.1 can now convert numbers to and from Roman numerals.",
		'size' => '1.8 MB',
		'release' => '2010/KavaServices43.txt',
		'screenshot_width' => 1200,
		'screenshot_height' => 750,
		'macosx' => '10.6',
	),
	'curator' => array(
		'icon' => 'Curator',
		'name' => 'Curator',
		'slogan' => 'The iTunes artwork manager.',
		'price' => '25',
		'link' => 'Curator/index.php',
		'paypal_name' => 'Curator',
		'kagi_name' => 'Curator_P2R',
		'kagi_id' => '368604895293',
		'product_id' => 6,
		'protocol' => 'curator',
		'version' => '1.4',
		'size' => '3.0 MB',
		'whatsnew' => "Curator 1.4 now gets higher resolution artwork from iTunes.",
		'release' => '2010/Curator13.txt',
		'screenshot_width' => 1040,
		'screenshot_height' => 683,
		'macosx' => '10.5',
	),
);

$bundle_products = array(
	'kavalife' => array(
		'icon' => 'KavaLife',
		'name' => 'KavaLife',
		'price' => '80',
		'link' => 'KavaLife/index.php',
		'paypal_name' => 'KavaLife',
		'kagi_name' => 'KavaLife_P2R',
		'kagi_id' => '3847-6493-7856',
		'products' => array('shoebox_express', 'kavatunes', 'kavamovies'),
	),
	'kavalife_pro' => array(
		'icon' => 'KavaLifePro',
		'name' => 'KavaLife Pro',
		'price' => '120',
		'link' => 'KavaLife/index.php',
		'paypal_name' => 'KavaLife Pro',
		'kagi_name' => 'KavaLife_Pro_P2R',
		'kagi_id' => '2791-2142-1779',
		'products' => array('shoebox_pro', 'kavatunes', 'kavamovies', 'iconquer', 'hyperimage', 'kavaservices'),
	),
	
);

$discontinued_products = array(
	'itunes_catalog' => array(
		'icon' => 'iTunesCatalog',
		'name' => 'iTunes Catalog',
		'slogan' => 'Create interactive music websites.',
		'link' => 'iTunesCatalog/index.php',
		'protocol' => 'itc',
		'version' => '2.2.2',
	),
	'translation_service' => array(
		'icon' => 'TranslationService',
		'name' => 'Translation Service',
		'slogan' => 'Translate text in any application.',
		'price' => '15',
		'link' => 'TranslationService/index.php',
		'protocol' => 'ts',
		'version' => '1.2.8',
	),
	'character_converter' => array(
		'icon' => 'CharacterConverter',
		'name' => 'Character Converter',
		'slogan' => 'Encode characters into HTML.',
		'price' => '15',
		'link' => 'CharacterConverter/index.php',
		'protocol' => 'cc',
		'version' => '1.3.3',
	),
);

$upgrade_products = array(
/*	'shoebox_pro_edition_upgrade' => array(
		'icon' => 'Shoebox',
		'name' => 'Shoebox Pro 2',
		'price' => '50',
		'link' => 'Shoebox/index.php',
		'paypal_name' => 'Shoebox Pro 2 upgrade',
		'kagi_name' => 'Shoebox_Pro_Upgrade_P2R',
		'upgrade_from' => 'Shoebox Express 2',
	),
	'shoebox_pro_version_upgrade' => array(
		'icon' => 'Shoebox',
		'name' => 'Shoebox Pro 2',
		'price' => '40',
		'link' => 'Shoebox/index.php',
		'paypal_name' => 'Shoebox Pro 2 upgrade',
		'kagi_name' => 'Shoebox_Pro_2_Upgrade_P2R',
		'upgrade_from' => 'Shoebox Pro 1.x',
	),
	'shoebox_pro_edition_version_upgrade' => array(
		'icon' => 'Shoebox',
		'name' => 'Shoebox Pro 2',
		'price' => '60',
		'link' => 'Shoebox/index.php',
		'paypal_name' => 'Shoebox Pro 2 upgrade',
		'kagi_name' => 'Shoebox_Pro_Upgrade_P2R',
		'upgrade_from' => 'Shoebox Express 1.x',
	),
	'shoebox_express_version_upgrade' => array(
		'icon' => 'Shoebox',
		'name' => 'Shoebox Express 2',
		'price' => '20',
		'link' => 'Shoebox/index.php',
		'paypal_name' => 'Shoebox Express 2 upgrade',
		'kagi_name' => 'Shoebox_Express_2_Upgrade_P2R',
		'upgrade_from' => 'Shoebox Express 1.x',
	),
*/	'shoebox_pro_upgrade' => array(
		'icon' => 'Shoebox',
		'name' => 'Shoebox Pro',
		'price' => '40',
		'link' => 'Shoebox/index.php',
		'paypal_name' => 'Shoebox Pro upgrade',
		'kagi_name' => 'Shoebox_Pro_Upgrade_P2R',
		'kagi_id' => '459955877872',
		'upgrade_from' => 'Shoebox Express',
	),
	'kavatunes_4_upgrade' => array(
		'icon' => 'KavaTunes',
		'name' => 'KavaTunes 4',
		'price' => '15',
		'link' => 'KavaTunes/index.php',
		'paypal_name' => 'KavaTunes 4 upgrade',
		'kagi_name' => 'KavaTunes_4_Upgrade_P2R',
		'kagi_id' => '865446080416',
		'upgrade_from' => 'KavaTunes 3<br>or iTunes Catalog',
	),
	'iconquer_4_upgrade' => array(
		'icon' => 'iConquer',
		'name' => 'iConquer 4',
		'price' => '15',
		'link' => 'iConquer/index.php',
		'paypal_name' => 'iConquer 4 upgrade',
		'kagi_name' => 'iConquer_4_Upgrade_P2R',
		'kagi_id' => '730414082806',
		'upgrade_from' => 'iConquer',
	),
	'hyperimage_3_upgrade' => array(
		'icon' => 'HyperImage',
		'name' => 'HyperImage 3',
		'price' => '15',
		'link' => 'HyperImage/index.php',
		'paypal_name' => 'HyperImage 3 upgrade',
		'kagi_name' => 'HyperImage_3_Upgrade_P2R',
		'kagi_id' => '343598314753',
		'upgrade_from' => 'HyperImage',
	),
	'kavatunes_upgrade' => array(
		'icon' => 'KavaTunes',
		'name' => 'KavaTunes',
		'price' => '15',
		'link' => 'KavaTunes/index.php',
		'paypal_name' => 'KavaTunes upgrade',
		'kagi_name' => 'KavaTunes_Upgrade_P2R',
		'kagi_id' => '558967681275',
		'upgrade_from' => 'iTunes Catalog 1.x',
	),
	'kavaservices_cc_upgrade' => array(
		'icon' => 'KavaServices',
		'name' => 'KavaServices',
		'price' => '15',
		'link' => 'KavaServices/index.php',
		'paypal_name' => 'KavaServices upgrade',
		'kagi_name' => 'KavaServices_Upgrade_P2R',
		'kagi_id' => '615476465358',
		'upgrade_from' => 'Character Converter',
	),
	'kavaservices_ts_upgrade' => array(
		'icon' => 'KavaServices',
		'name' => 'KavaServices',
		'price' => '15',
		'link' => 'KavaServices/index.php',
		'paypal_name' => 'KavaServices upgrade',
		'kagi_name' => 'KavaServices_Upgrade_P2R',
		'kagi_id' => '615476465358',
		'upgrade_from' => 'Translation Service',
	),
);

function upgrade_key($program) {
	if ($program == 'KavaTunes') return 'kavatunes_4_upgrade';
	if ($program == 'iTunes Catalog') return 'kavatunes_4_upgrade';
	if ($program == 'Shoebox Express') return 'shoebox_pro_upgrade';
	if ($program == 'Character Converter') return 'kavaservices_cc_upgrade';
	if ($program == 'Translation Service') return 'kavaservices_ts_upgrade';
	return null;
}

$hyperimage20 = array('discount' => 0.8, 'allowed' => array('hyperimage'));

$coupons = array(
	'MONOCHROME' => $hyperimage20,
	'1435MM' => $hyperimage20,
	'REALITY' => $hyperimage20,
	'FULLTEAMAHEAD' => $hyperimage20,
	'AEONMOUNTAIN' => $hyperimage20,
	'BISHONEN' => $hyperimage20,
	'MACWORLD' => array('discount' => 0.8, 'allowed' => array('all')),
);

?>